- name: Deploy Docker Compose project
  hosts: 127.0.0.1
  connection: local
  vars:
    compose_project_dir: "/home/danila/compose_ansible"
    compose_file: "docker-compose.yml"
    compose_project_name: "test_compose"
  tasks:
    - name: Pull repository
      command: git pull
      
    - name: Buld and start Docker Compose project
      command: podman-compose -f {{ compose_project_dir }}/{{ compose_file }} -p {{ compose_project_name }} up -d --build    
      environment:
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
      args:
        chdir: "{{ compose_project_dir }}"

