- name: Deploy Docker Compose project
  hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    compose_project_dir: "/home/danila/compose_ansible"
    compose_file: "docker-compose.yml"
    compose_project_name: "test_compose"
  tasks:
    - name:
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: Install docker/podman engine
      pip:
        name:
          - podman
          - podman-compose
        state: present
    - name: Buld and start Docker Compose project
      command: podman-compose -f {{ compose_project_dir }}/{{ compose_file }} -p {{ compose_project_name }} up -d --build    
      environment:
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
      args:
        chdir: "{{ compose_project_dir }}"

