- name: Deploy Docker Compose project
  hosts: 127.0.0.1
  connection: local
  vars:
    compose_project_dir: "/home/danila/compose_ansible"
    compose_file: "docker-compose.yml"
    compose_project_name: "test_compose"
  tasks:
    - name: Запустить docker-compose
      community.docker.docker_compose:
        project_name: test_compose_podman
        project_src: /home/danila/compose_ansible
        state: present

