- name: Deploy Docker Compose project
  hosts: all
  vars:
    compose_project_dir: "./"
    compose_file: "docker-compose.yml"
    compose_project_name: "test_compose"
  tasks:
    - name: Test connection
      command: pwd
    - name: Create test file on remote host
      command: touch test.txt
    - name: Build and start Docker Compose project
      command: >
        docker-compose -f {{ compose_project_dir }}/{{ compose_file }} -p {{ compose_project_name }} up -d --build
      args:
        chdir: "{{ compose_project_dir }}"
