- name: Deploy Docker Compose project
  hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    compose_project_dir: "./"
    compose_file: "docker-compose.yml"
    compose_project_name: "test_compose"
  tasks:
    - name: Install Docker Engine
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        update_cache: yes
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    - name: Install Docker Compose
      command: >
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" \
        -o /usr/local/bin/docker-compose && \
        chmod +x /usr/local/bin/docker-compose
    # Сборка и запуск Docker Compose проекта
    - name: Build and start Docker Compose project
      command: >
        docker-compose -f {{ compose_project_dir }}/{{ compose_file }} -p {{ compose_project_name }} up -d --build
      args:
        chdir: "{{ compose_project_dir }}"
