name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-playbooks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install ansible -y

    - name: Ansible Run Playbook
      run: ansible-playbook -i ./ansible_deploy_apt.yml -u ${{ secrets.USERNAME }} --private-key ${{ secrets.PRIVATE_KEY }}
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
        ANSIBLE_REMOTE_USER: ${{ secrets.USERNAME }}
        ANSIBLE_PRIVATE_KEY_FILE: ${{ secrets.PRIVATE_KEY }}

