name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-playbooks:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.IP_ADDRESS }}
        username: ${{ secrets.USERNAME }}
        key : ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: touch test1.txt
    
#       - name: Checkout Code
#         uses: actions/checkout@v2
      
#       - name: Setup SSH 
#         shell: bash
#         run: |
#          eval `ssh-agent -s`
#          mkdir -p /home/runner/.ssh/
#          touch /home/runner/.ssh/id_rsa
#          echo -e "${{secrets.PRIVATE_KEY}}" > /home/runner/.ssh/id_rsa
#          chmod 700 /home/runner/.ssh/id_rsa
#          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 ${{secrets.IP_ADDRESS}} >> /home/runner/.ssh/known_hosts

#       - name: Ansible Playwright
#   # You may pin to the exact commit or the version.
#   # uses: aimerib/ansible-playwright@06276a1dd2ac67b31187164a21463632077ffec0
#         uses: aimerib/ansible-playwright@v2.7.7
#         with:
#           playbook: ./ansible_deploy_apt.yml
#           # Ansible Galaxy requirements filepath  
#           directory: ./
#           # SSH private key used to connect to the host
#           private-key: /home/runner/.ssh/id_rsa
#           # SSH User to use when connecting to host
#           user: mdev
#           # Custom content to write into hosts
#           inventory: |
#             [remote_host]
#             148.251.4.54          
          #vault_password: # optional
            # Contents of SSH known_hosts file
#           known_hosts: /home/runner/.ssh/known_hosts
          # Extra options that should be passed to ansible-playbook command
          #options: # optional
          # Set to "true" if root is required for running your playbook
          #sudo: # optional
          # Set to "true" if the Ansible output should not include colors (defaults to "false")
          #no_color: # optional
          
          
#       - name: Run playbook
#         uses: dawidd6/action-ansible-playbook@v2
#         with:
#         # Required, playbook filepath
#           playbook: ./ansible_deploy_apt.yml
#           # Optional, directory where playbooks live
#           directory: ./
#           # Optional, SSH private key
#           key: ${{secrets.PRIVATE_KEY}}
#           # Optional, literal inventory file contents
#           inventory: |
#             [all]
#             ${{ secrets.IP_ADDRESS }}
            
#             [remote_host]
#             ${{ secrets.IP_ADDRESS }}
#           # Optional, SSH known hosts file content
#           known_hosts: .known_hosts
