name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  run-playbooks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install ansible -y
    
    - name: Check where i am
      run: ls -la

    - name: Ansible Run Playbook
      run: ansible-playbook ./ansible_deploy.yml -i localhost, --connection=local #-i #Host
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
        ANSIBLE_REMOTE_USER: ${{ secrets.USERNAME }}
        ANSIBLE_PRIVATE_KEY_FILE: ${{ secrets.PRIVATE_KEY }}

