name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-playbooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
        # Required, playbook filepath
          playbook: ./ansible_deploy_apt.yml
          # Optional, directory where playbooks live
          directory: ./
          # Optional, SSH private key
          key: ${{secrets.PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all]
            ${{ secrets.IP_ADDRESS }}
          # Optional, SSH known hosts file content
          known_hosts: .known_hosts
