# name: Docker Image CI

 on:
   push:
     branches: [ "master" ]
   pull_request:
     branches: [ "master" ]
 jobs:
   run-playbooks:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
         uses: actions/checkout@v2
         
       - name: Clone repository on remote host
         run: |
              git remote add deploy ${{ secrets.USER }}@${{ secrets.IP_ADDRESS }}:/home/mdev/server_git.git
              git push bare master
