name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run-playbooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Connect ssh
        uses: appleboy/ssh-action@v0.0.7
        with:
          host: ${{ secrets.IP_ADDRESS }}
          username: ${{ secrets.USER }}
          port: 22
          key: ${{ secrets.PRIVATE_KEY }}
          script: touch /home/${{ secrets.USER }}/1.txt

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
        # Required, playbook filepath
          playbook: ./ansible_deploy_apt.yml
          # Optional, directory where playbooks live
          directory: ./
          # Optional, SSH private key
          key: ${{secrets.PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: ${{ secrets.IP_ADDRESS }}
          # Optional, SSH known hosts file content
          known_hosts: ${{ secrets.PUB_KEY}}
